source 'https://github.com/CocoaPods/Specs.git'





def import_pods
  pod "ABMSoundCloudAPI", :path => "../"
  
  pod 'SVProgressHUD', '~> 1.1'
  pod 'UIAlertView-Blocks', '~> 1.0'
end





target 'ABMSoundCloudAPI', :exclusive => true do
  import_pods
end

target 'Tests', :exclusive => true do
  import_pods
end
